apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "minio.fullname" . }}-post-install-check"
  labels:
    {{- include "minio.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ include "minio.fullname" . }}-post-install-check"
      labels:
        {{- include "minio.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: minio-check
        image: curlimages/curl:7.86.0
        command:
        - /bin/sh
        - -c
        - |
          # Wait for MinIO to initialize
          echo "Waiting for MinIO to initialize..."
          sleep 10
          
          # Use external hostname that we know works
          EXTERNAL_HOST="minio-api-test.apps.ecoeng-alex-devsno.coreostrain.me"
          
          echo "Checking MinIO API endpoint..."
          RETRY_COUNT=0
          MAX_RETRIES=30
          
          until [ $RETRY_COUNT -ge $MAX_RETRIES ]
          do
            HTTP_CODE=$(curl -k -s -f -o /dev/null -w "%{http_code}" "https://${EXTERNAL_HOST}/minio/health/live")
            if [ "$HTTP_CODE" = "200" ]; then
              echo "SUCCESS: MinIO API is ready! (HTTP ${HTTP_CODE})"
              exit 0
            fi
            RETRY_COUNT=$((RETRY_COUNT+1))
            echo "MinIO API not yet ready (HTTP ${HTTP_CODE}), retrying... ($RETRY_COUNT/$MAX_RETRIES)"
            sleep 5
          done
          
          echo "ERROR: MinIO API failed to become ready within timeout period"
          exit 1 