apiVersion: batch/v1
kind: Job
metadata:
  name: "{{- include "ingestion-pipeline.name" . }}"
  labels: 
    pipelines.kubeflow.org/v2_component: 'true'
spec:
  selector:
  template:
    metadata:
      labels:
        pipelines.kubeflow.org/v2_component: 'true'
    spec:
      containers:
        - args:
            - -ec
            - |-
              pip install kfp[kubernetes]
              python3 /ingestion-script/ingestion.py
          command:
            - /bin/bash
          env:
            - name: LLAMASTACK_BASE_URL
              value: "http://llamastack.{{ .Release.Namespace }}.svc.cluster.local:8321"
            - name: DS_PIPELINE_URL
              value: "https://ds-pipeline-dspa.{{ .Release.Namespace }}.svc.cluster.local:8888"
            - name: SOURCE
              value: "{{ .Values.source }}"
          image: python:3.10-slim
          imagePullPolicy: IfNotPresent
          name: create-ingestion-pipeline
          volumeMounts:
            - mountPath: /ingestion-script
              name: ingestion-python-script-volume
            - mountPath: /.local
              name: dot-local
      restartPolicy: Never
      volumes:
        - configMap:
            defaultMode: 420
            name: "{{- include "ingestion-pipeline.name" . }}-pipeline-config"
          name: ingestion-python-script-volume
        - emptyDir: {}
          name: dot-local
